export {default as Navbar} from './navbar'
export {default as UserHome} from './user-home'
export {Login, Signup} from './auth-form'
export {default as SearchMovies} from './movies/userChoices/SearchMovies'
export {default as UserChoices} from './movies/userChoices/UserChoices'
export {default as PickKeywords} from './movies/userChoices/PickKeywords'
export {default as PickGenre} from './movies/userChoices/PickGenre'
export {default as SignUpData} from './signup/SignUpData'
export {default as Flick} from './signup/Flick'
export {default as Loading} from './loading'
export {default as Whatflix} from './movies/userChoices/Whatflix'
export {default as Favorites} from './movies/Favorites'
export {default as WatchList} from './movies/WatchList'

